---
- name: install docker
  hosts: aws_ec2
  become: true
  tasks:
    - name: install docker
      dnf:
        name: docker
        update_cache: true
        state: present
    - name: install pip
      dnf: 
        name: python3-pip
        state: present 
    - name: start the docker service
      systemd:
        name: docker
        state: started