---
- name: wait ssh connection
  hosts: aws_ec2
  gather_facts: False
  tasks:
    - name: ensure ssh port open
      port: 22
      wait_for:
        delay: 10
        timeout: 80
        search_regex: OpenSSH
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      vars:
        ansible_connection: local
- name: install docker
  hosts: aws_ec2
  become: true
  tasks:
    - name: install docker
      dnf:
        name: docker
        update_cache: true
        state: present
    - name: install pip
      dnf: 
        name: python3-pip
        state: present 
    - name: start the docker service
      systemd:
        name: docker
        state: started